version: 2
jobs:
  frontend_lint:
    docker:
      - image: node:10.8.0
    working_directory: /home/h4i-recruitment
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            yarn
            yarn format:check
  backend_lint:
    docker:
      - image: node:10.8.0
    working_directory: /home/h4i-recruitment
    steps:
      - checkout
      - run:
          command: |
            cd backend
            yarn
            yarn format:check
  # backend_test:
  #   docker:
  #     - image: node:10.8.0
  #   working_directory: /home/h4i-recruitment
  #   steps:
  #     - checkout
  #     - run:
  #         command: |
  #           cd backend
  #           yarn
  #           yarn test
  frontend_build:
    docker:
      - image: node:10.8.0
    working_directory: /home/h4i-recruitment
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            yarn
            yarn build
workflows:
  version: 2
  build_test:
    jobs:
      - frontend_lint
      - frontend_build
      - backend_lint
      - backend_test
