version: 2
jobs:
  frontend_lint:
    docker:
      - image: node:14.5.0
    working_directory: /home/h4i-recruitment
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            yarn
            yarn format:check
  backend_lint:
    docker:
      - image: node:14.5.0
    working_directory: /home/h4i-recruitment
    steps:
      - checkout
      - run:
          command: |
            cd backend
            yarn
            yarn format:check
  backend_test:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: ~/home/h4i-recruitment
    steps:
      - checkout
      - run:
          command: |
            docker-compose -f docker-compose.test.yml run backend
  frontend_build:
    docker:
      - image: node:14.5.0
    working_directory: /home/h4i-recruitment
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            yarn
            yarn build
workflows:
  version: 2
  build_test:
    jobs:
      - frontend_lint
      - frontend_build
      - backend_lint
      - backend_test
